### ISSUE TITLE
It seems that ARLocationOrientation.cs is not working properly.

### ISSUE THREAD

**Issue by varunitestudio** [dmbfm/unity-ar-gps-location-issues#11]
**Describe the bug**
If you build and run a program, the object is placed, but the direction is not very accurate.

It's arranged about 10 times in the direction I want.

The device I use comes with Input.compass..headingAcuracy = 0.
Is there any way to improve the accuracy of the direction?

**Screenshots and Videos**
If applicable, add screenshots and videos to help explain your problem.

**Desktop (please complete the following information):**
 - OS: Windows 10
 - Unity Version: Unity3D 2018.3.9f1

**Smartphone (please complete the following information):**
 - Device: [e.g. iPhone6] Samsung Galaxy Tap s4
 - OS: [e.g. iOS8.1] Android 9

**Additional context**

**Comment by viniad** [comment]
You can get a better precision of direction by calibrating the magnetic compass of your phone, here: https://support.google.com/maps/answer/2839911?co=GENIE.Platform%3DAndroid&hl=en

**Comment by dmbfm** [comment]
Yes, the orientation quality sadly will vary a lot from device to device on Android. 

As @viniad pointed out, calibrating the compass usually helps a lot.

In my experience, tablets usually are not equipped with very good location sensors, but I never used
a Galaxy Tap so I can't say for sure in this case.

Do you have another device to test and compare results with? 

Thanks!

**Comment by TimHeessels** [comment]
@dmbfm I seem to have the same problem, tested on two android devices (exactly the same results). It seems the rotation differs every time. The compass in the debug-ui shows the same direction constantly so i would think this is correct. If you cover the lens to stop ar from working and direct the camera to a different place the rotation also changes.

**Comment by dmbfm** [comment]
@TimHeessels Are you able to record a video showing this effect?

When you cover the lens, the AR tracking will stop and restart, and probably change the orientation, hence this happens.

The ARLocationManager (https://docs.unity-ar-gps-location.com/guide/#arlocationmanager) has a  `Restart When AR Tracking Is Restored` setting which should counter this by resetting the whole AR+GPS Location system. This happens even if this setting is checked? 

Thanks!

**Comment by TimHeessels** [comment]
@dmbfm Hey Daniel, I've send you an email with the video explaining the issue :)

**Comment by yahavt** [comment]
Hey
Anything new on this bug? I am having the same issue...

**Desktop (please complete the following information):**
OS: Mac
Unity Version: Unity3D 2019.2.17f1

**Smartphone**:
Device: [e.g. iPhone6] iPhone6s, iPhoneX, iPhoneXMax, iPhone11
OS: [e.g. iOS8.1] iOS11, iOS13+
Version [e.g. 22]

**Comment by dmbfm** [comment]
@yahavt Hi, which version of the asset are you using? If you can send me a screen recording of the app, either here or to daniel.mbfm@gmail.com. Thanks

**Comment by yahavt** [comment]
@dmbfm I am using v3.2.0
I just saw there's a new version in the asset store, I will update and check if it helps.
My use case is a bit complicated to record:
I have 3D objects in AR that represent a device GPS location.
When I start the app the 3D objects position in the correct place in the AR scene (approximately where the 2nd mobile phone is)

Every

**Comment by yahavt** [comment]
@dmbfm
I am using v3.2.0
I just saw there's a new version in the asset store, I will update and see if it helps.

My use case is a bit complicated to record and will be easier to explain :

- I have 3D objects that represent in my AR scene a mobile device GPS location.

- When I start the app on my mobile phone - a 3D object is shown correctly in the AR scene (approximately where the 2nd mobile phone is).

- When the 2nd mobile phone moves - I see the 3D object moves correctly! I also used the distance calculation using the helpers RawGpsDistance and SceneDistance and the values are current.

- BUT once I start walking with my device the 3D object of the 2nd device is not positioned correctly, which I think the problem here is the orientation (Notice that the distance calculated using RawGpsDistance is correct and the distance of SceneDistance is **incorrect**).

Thoughts?

**Comment by dmbfm** [comment]
Let me see if I understand correctly.

The second device constantly sends its location to the first device.

The first device positions an object at the location using "PlaceAtLocation" and constantly 
updates the location as the second device moves.

Is that correct?

**Comment by yahavt** [comment]
Yes

**Comment by dmbfm** [comment]
What settings do you have on the PlaceAtLocation and/or LocatioProvider?

Because in this case I believe it would be best to remove all filters, e.g., set Max Number Of Location Updates to 0, and on LocationProvider

![image](https://user-images.githubusercontent.com/8743306/74178276-067df480-4c1a-11ea-8303-77e14c6c5829.png)

Set all of these to zero, except Accuracy radius, which you can set to, let's say, 50.

Because on your scenario you want to have almost the raw data being used.

**Comment by yahavt** [comment]
@dmbfm Thank you for the quick replies!
After I updated to the latest release it fixed most of the issues. After a few more tweaks and it now works!! Thanks again!

**Comment by dmbfm** [comment]
Great to hear, thanks!

Closing the issue for now.
