### ISSUE TITLE
Placing objects at distant locations

### ISSUE THREAD

**Issue by seanbiganski** [dmbfm/unity-ar-gps-location-issues#26]
Do you have any suggestions on how to point the user towards an object that may be thousands of feet away? I have tried scaling the object up and down based on the distance but that can be problematic for a number of reasons like the far clipping plane. Thanks.

**Comment by dmbfm** [comment]
Hi!

That is a good question. 

Out of the top of my head, you could place a clone of the object at the same direction, but with a different distance (i.e.,  along the direction of RealPositionVector - CameraPositionVector). The clone would only be shown if the realobject is farther away than the far clip plane.

Do you think this is a viable way to do this?  We could add a feature for this in a next release, since it can be pretty useful if it works.

**Comment by seanbiganski** [comment]
I thought about the approach of placing the object between the camera and the AR marker. I definitely think that would have worked but I landed on a different approach. At least for now. I am using this asset https://assetstore.unity.com/packages/tools/gui/waypoint-indicators-153472 to show which directions the GPS markers are in.

So far, it's working quite well. Thanks for responding, I will go ahead and close this thread.
